version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: senhaforte
    volumes:
      - mongodb_data:/data/db
    networks:
      - dev_net

networks:
  dev_net:

volumes:
  mongodb_data:
